Repository Eccoar/2020.2-eccoar_front-end, pull requests merged in 2021-03, with the labels that each got.

#2 Solve #73 Criação de Componente Botão
  docker-compose.yml
  src/App.test.tsx
  src/App.tsx
  src/assets/Echo.svg
  src/assets/MegaPhone.svg
  src/assets/Next.svg
  src/components/complainButton.tsx
  src/index.tsx
  src/reportWebVitals.ts
  src/styles/complainButton.scss
  src/styles/main.scss
Labels: good first issue

#3 Solve #71 Criação de componente estático - NavBar
  src/App.tsx
  src/assets/isotipo.svg
  src/components/Navbar.tsx
  src/styles/navbar.scss
Labels: good first issue

#4 Solve #72 Criação do BackGround do Front-end
  src/App.css
  src/assets/Background.png
  src/styles/main.scss
Labels: good first issue

#5 * Solve #76 Card e upvote de denúncia
  src/App.tsx
  src/assets/EchoImage.png
  src/components/complainCard.tsx
  src/styles/complainCard.scss
Labels: good first issue

#7 Solve #70 Estudo de testes do front
  docs/testing.md
  package.json
  src/components/Button.tsx
  src/tests/components/Button.test.tsx
Labels: documentation, test

#6 * Solve #75 Criação de componente - Input
  src/App.tsx
  src/components/inputBasic.tsx
  src/styles/inputBasic.scss
Labels: good first issue

#9 Solve #101 drawer component
  src/App.tsx
  src/assets/Close.svg
  src/assets/Moon.svg
  src/assets/Sun.svg
  src/components/Backdrop.tsx
  src/components/Drawer.tsx
  src/components/Navbar.tsx
  src/context/theme.tsx
  src/styles/base/_app.scss
  src/styles/base/_body.scss
  src/styles/base/_index.scss
  src/styles/components/_backdrop.scss
  src/styles/components/_drawer.scss
  src/styles/components/_index.scss
  src/styles/components/_navbar.scss
Labels: good first issue

#11 REVIEW #93 Formulário de denúncias
  package-lock.json
  package.json
  src/App.test.tsx
  src/App.tsx
  src/components/Backdrop.tsx
  src/components/Drawer.tsx
  src/components/inputBasic.tsx
  src/context/theme.tsx
  src/pages/Home.tsx
  src/pages/SubmitComplain/SubmitComplaintConclude.tsx
  src/pages/SubmitComplain/SubmitComplaintGeolocation.tsx
  src/pages/SubmitComplain/SubmitComplaintInfos.tsx
  src/pages/SubmitComplain/SubmitComplaitOptionPhoto.tsx
  src/pages/SubmitComplain/SubmitComplaitPhoto.tsx
  src/routes.tsx
  src/services/api.ts
  src/services/complaint.ts
  src/styles/abstract/_mixins.scss
  src/styles/base/_root.scss
  src/styles/layouts/_home.scss
  src/styles/layouts/_index.scss
  src/styles/layouts/_submitComplaintConclude.scss
  src/styles/layouts/_submitComplaintGeolocation.scss
  src/styles/layouts/_submitComplaintInfos.scss
  src/styles/layouts/_submitComplaintOptionPhoto.scss
  src/styles/layouts/_submitComplaintPhoto.scss
  src/tests/components/Button.test.tsx
  src/tests/pages/SubmitComplain/SubmitComplainGeolocation.test.tsx
  src/tests/pages/SubmitComplain/SubmitComplaintConclude.test.tsx
  src/tests/pages/SubmitComplain/SubmitComplaintInfos.test.tsx
  src/tests/pages/SubmitComplain/SubmitComplaintPhoto.test.tsx
  src/tests/pages/SubmitComplain/SubmitComplaitOptionPhoto.test.tsx
Labels: enhancement

#10 REVIEW #88 - Feed de denúncias
  package-lock.json
  src/components/Button.tsx
  src/components/Drawer.tsx
  src/components/complainCard.tsx
  src/pages/Home.tsx
  src/pages/SubmitComplain/SubmitComplaintGeolocation.tsx
  src/pages/SubmitComplain/SubmitComplaintInfos.tsx
  src/pages/SubmitComplain/SubmitComplaitOptionPhoto.tsx
  src/pages/SubmitComplain/SubmitComplaitPhoto.tsx
  src/services/complaint.ts
  src/styles/base/_app.scss
  src/styles/base/_body.scss
  src/styles/base/_root.scss
  src/styles/complainCard.scss
  src/styles/components/_button.scss
  src/styles/components/_card.scss
  src/styles/components/_drawer.scss
  src/styles/components/_input.scss
  src/styles/components/_navbar.scss
  src/styles/layouts/_home.scss
  src/styles/layouts/_index.scss
  src/styles/layouts/_submitComplaint.scss
  src/styles/layouts/_submitComplaintConclude.scss
  src/styles/layouts/_submitComplaintGeolocation.scss
  src/styles/layouts/_submitComplaintInfos.scss
  src/styles/layouts/_submitComplaintOptionPhoto.scss
  src/styles/layouts/_submitComplaintPhoto.scss
  src/tests/components/Button.test.tsx
  src/tests/components/ComplainCard.test.tsx
Labels: bug, good first issue, test

#12 [REVIEW] #117 Arrumando cores, responsividade e background
  src/components/Drawer.tsx
  src/components/Navbar.tsx
  src/styles/base/_app.scss
  src/styles/components/_drawer.scss
  src/styles/components/_navbar.scss
Labels: bug
