Repository Eccoar/2020.2-eccoar_front-end, pull requests merged in 2021-05, with the labels that each got.

#31 Solve #195 Cobertura de testes
  jest.config.js
  package.json
  src/App.tsx
  src/components/Drawer.tsx
  src/components/Navbar.tsx
  src/pages/ComplaintDetails.tsx
  src/pages/SubmitComplain/SubmitComplaintGeolocation.tsx
  src/services/complaint.ts
  src/tests/App.test.ts
  src/tests/components/NavBar.test.tsx
  src/tests/components/NavBarArrow.test.tsx
  src/tests/pages/ComplaitDetails.test.tsx
  src/tests/pages/Register/RegisterEmail.test.tsx
  src/tests/pages/SubmitComplain/SubmitComplaintGeolocation.test.tsx
  src/tests/pages/SubmitComplain/SubmitComplaintPhoto.test.tsx
  src/tests/routes.test.ts
  src/tests/services/complaint.test.ts
  src/tests/utils/geolocation.test.ts
Labels: MDS, test

#24 Solve #139 Retirar upvote e voto de confirmação
  src/components/Button.tsx
  src/components/complainCard.tsx
  src/pages/ComplaintDetails.tsx
  src/pages/Home.tsx
  src/services/complaint.ts
  src/styles/layouts/_complaintDetails.scss
  src/tests/components/ComplainCard.test.tsx
  src/tests/pages/ComplaintDetails.test.tsx
  src/tests/pages/ComplaitDetails.test.tsx
Labels: FEATURE, MDS

#25 Solve #153 Retirada de denúncia
  src/pages/ComplaintDetails.tsx
  src/pages/SubmitComplain/SubmitComplaintConclude.tsx
  src/pages/SubmitComplain/SubmitComplaintGeolocation.tsx
  src/services/complaint.ts
  src/styles/layouts/_complaintDetails.scss
  src/tests/pages/ComplaintDetails.test.tsx
  src/tests/pages/Register/RegisterEmail.test.tsx
  src/tests/pages/home/home.test.tsx
Labels: FEATURE, MDS

#33 Hotfix #191 Flaggr e quantidade de votos
  src/services/complaint.ts
Labels: HOTFIX

#29 Solve #165 - Autenticação de usuário
  package-lock.json
  package.json
  src/assets/logo.svg
  src/components/Drawer.tsx
  src/components/LocationMarker.tsx
  src/components/Navbar.tsx
  src/components/inputBasic.tsx
  src/context/auth.tsx
  src/pages/ComplaintDetails.tsx
  src/pages/FirstPage.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Register/RegisterAdress.tsx
  src/pages/Register/RegisterEmail.tsx
  src/pages/Register/RegisterName.tsx
  src/pages/SubmitComplaint/SubmitComplaintConclude.tsx
  src/pages/SubmitComplaint/SubmitComplaintGeolocation.tsx
  src/pages/SubmitComplaint/SubmitComplaintInfos.tsx
  src/pages/SubmitComplaint/SubmitComplaitOptionPhoto.tsx
  src/pages/SubmitComplaint/SubmitComplaitPhoto.tsx
  src/routes.tsx
  src/services/api.ts
  src/services/complaint.ts
  src/styles/components/_drawer.scss
  src/styles/layouts/_index.scss
  src/styles/layouts/_login.scss
  src/styles/layouts/_register.scss
  src/tests/components/LocationMarker.test.tsx
  src/tests/components/NavBar.test.tsx
  src/tests/contexts/auth.test.tsx
  src/tests/pages/ComplaintDetails.test.tsx
  src/tests/pages/Login.test.tsx
  src/tests/pages/Register/RegisterEmail.test.tsx
  src/tests/pages/Register/RegisterName.test.tsx
  src/tests/pages/Register/registerAddress.test.tsx
  src/tests/pages/SubmitComplaint/SubmitComplaintConclude.test.tsx
  src/tests/pages/SubmitComplaint/SubmitComplaintGeolocation.test.tsx
  src/tests/pages/SubmitComplaint/SubmitComplaintInfos.test.tsx
  src/tests/pages/SubmitComplaint/SubmitComplaintPhoto.test.tsx
  src/tests/pages/SubmitComplaint/SubmitComplaitOptionPhoto.test.tsx
  src/tests/services/complaint.test.ts
Labels: HARD, MDS, US

#34 Solve #227 HOTFIX Sonar URL
  .gitlab-ci.yml
Labels: ANALYTICS, EPS, HOTFIX
